/*
 * commands.c
 *
 *  Created on: Mar 23, 2013
 *      Author: franz
 */

#include <commands.h>
#include <stdio.h>
#include <stdlib.h>
#include <task.h>

portBASE_TYPE simpleHelloCmd( int8_t *pcWriteBuffer, size_t xWriteBufferLen, const int8_t *pcCommandString )
{
    /* For simplicity, this function assumes the output buffer is large enough
    to hold all the text generated by executing the vTaskList() API function,
    so the xWriteBufferLen parameter is not used. */
    ( void ) xWriteBufferLen;

    /* pcWriteBuffer is used directly as the vTaskList() parameter, so the table
    generated by executing vTaskList() is written directly into the output
    buffer. */

    sprintf((char*)pcWriteBuffer, "Hello World!");

    //GPIO_SetBits(GPIOE,GPIO_Pin_10);

    /* The entire table was written directly to the output buffer.  Execution
    of this command is complete, so return pdFALSE. */
    return pdFALSE;
}

portBASE_TYPE storeInFlash( int8_t *pcWriteBuffer, size_t xWriteBufferLen, const int8_t *pcCommandString )
{
    ( void ) xWriteBufferLen;

    uint32_t *mydata;
    uint32_t storeData = 0;
    mydata = (uint32_t*)USERFLASH_MEMORY_BASE;

	int8_t *pcParameter1;

	portBASE_TYPE xParameter1StringLength;
	 /* Obtain the name of the destination file, and the length of its name. */
    pcParameter1 = (int8_t*)FreeRTOS_CLIGetParameter( pcCommandString, 1, &xParameter1StringLength);
	/* Null terminator. */
	pcParameter1[ xParameter1StringLength ] = 0x00;

	storeData = atoi((char*)pcParameter1);

    FLASH_Unlock();
    /* Clear pending flags (if any) */
    FLASH_ClearFlag(FLASH_FLAG_EOP    | FLASH_FLAG_OPERR  | FLASH_FLAG_WRPERR |
                    FLASH_FLAG_PGAERR | FLASH_FLAG_PGPERR | FLASH_FLAG_PGSERR);
    if (FLASH_EraseSector(FLASH_Sector_11, VoltageRange_3) != FLASH_COMPLETE)
    {
    	sprintf((char*)pcWriteBuffer, "Error while erasing!");
    	FLASH_Lock();
        return pdFALSE;
    }
	if (FLASH_ProgramWord((uint32_t)mydata, storeData ) != FLASH_COMPLETE)
	{
		sprintf((char*)pcWriteBuffer, "Error while programming!");
		FLASH_Lock();
	    return pdFALSE;
	}
	FLASH_Lock();
	sprintf((char*)pcWriteBuffer, "OK! %p %ld", mydata, *mydata);

    /* The entire table was written directly to the output buffer.  Execution
    of this command is complete, so return pdFALSE. */
    return pdFALSE;
}

portBASE_TYPE getFromFlash( int8_t *pcWriteBuffer, size_t xWriteBufferLen, const int8_t *pcCommandString )
{
    ( void ) xWriteBufferLen;

    uint32_t *mydata;
    mydata = (uint32_t*)USERFLASH_MEMORY_BASE;

	sprintf((char*)pcWriteBuffer, "Value: %ld", *mydata);

    /* The entire table was written directly to the output buffer.  Execution
    of this command is complete, so return pdFALSE. */
    return pdFALSE;
}



portBASE_TYPE simpleParamCmd( int8_t *pcWriteBuffer, size_t xWriteBufferLen, const int8_t *pcCommandString )
{

	int8_t *pcParameter1;

	portBASE_TYPE xParameter1StringLength;

	 /* Obtain the name of the destination file, and the length of its name. */
    pcParameter1 = (int8_t*)FreeRTOS_CLIGetParameter( pcCommandString, 1, &xParameter1StringLength);

	/* Parameters. */
	pcParameter1[ xParameter1StringLength ] = 0x00;

    snprintf((char*)pcWriteBuffer, xWriteBufferLen, (char*)pcParameter1);

    /* The entire table was written directly to the output buffer.  Execution
    of this command is complete, so return pdFALSE. */
    return pdFALSE;
}

